/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import javax.swing.JOptionPane;

/**
 *
 * @author maury
 */
public class ventana extends javax.swing.JInternalFrame {
 int c=0;
 int c2=0;
    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        opsuma = new javax.swing.JRadioButton();
        jPanel15 = new javax.swing.JPanel();
        opresta = new javax.swing.JRadioButton();
        jPanel16 = new javax.swing.JPanel();
        opmultiplicacion = new javax.swing.JRadioButton();
        jPanel17 = new javax.swing.JPanel();
        opdiv = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtnum1 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        txtnum2 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        Bresultado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btnsuma = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnresta = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        btnmulti = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        btndivision = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.setLayout(new java.awt.GridLayout(4, 4));

        opsuma.setText("Suma");
        opsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opsumaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opsuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opsuma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel14);

        opresta.setText("resta");
        opresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oprestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(opresta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opresta, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel15);

        opmultiplicacion.setText("Multiplicaciion");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opmultiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opmultiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel16);

        opdiv.setText("Division");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opdiv, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opdiv, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel17);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(80, 100));
        jPanel2.setLayout(new java.awt.GridLayout(4, 4));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7);

        txtnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnum1ActionPerformed(evt);
            }
        });
        txtnum1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnum1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtnum1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtnum1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        txtnum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnum2ActionPerformed(evt);
            }
        });
        txtnum2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnum2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtnum2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtnum2, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bresultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bresultado, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setMaximumSize(new java.awt.Dimension(100, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel2.setText("                                                                    Operciones Aritmeticas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel4.setLayout(new java.awt.GridLayout(1, 4));

        jPanel18.setLayout(new java.awt.GridLayout(2, 2));

        jButton5.setText("Calcular");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton5);

        jButton6.setText("Cerrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton6);

        jPanel4.add(jPanel18);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setPreferredSize(new java.awt.Dimension(200, 143));
        jPanel5.setLayout(new java.awt.GridLayout(4, 4));

        btnsuma.setBackground(new java.awt.Color(51, 255, 51));
        btnsuma.setFont(new java.awt.Font("MV Boli", 0, 11)); // NOI18N
        btnsuma.setForeground(new java.awt.Color(0, 51, 51));
        btnsuma.setText("Suma");
        btnsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnsuma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnsuma, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel10);

        btnresta.setText("Resta");
        btnresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnresta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnresta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel11);

        btnmulti.setText("Multiplicacion");
        btnmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnmulti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnmulti, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel12);

        btndivision.setText("Diivision");
        btndivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btndivision, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btndivision, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel13);

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnum1ActionPerformed

    private void btnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumaActionPerformed
        // TODO add your handling code here:
         String n1,n2;
         n1 = txtnum1.getText();
         n2 = txtnum2.getText();
          Validaciones val = new Validaciones();
          if (val.validarEnteros(n1).equals("decimal")){
              //JOptionPane.showMessageDialog(null, "Hola");
              float a= Float.parseFloat(n1);
              if (val.validarEnteros(n2).equals("decimal")){
                  float b = Float.parseFloat(n2);
                  float r = a + b;
                  Bresultado.setText(Float.toString(r));
                    }else if (val.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                float r = a + b;
                Bresultado.setText(Float.toString(r));
            
                  
              }
          }else if(val.validarEnteros(n1).equals("entero")){
              int a = Integer.parseInt(n1);
              if (val.validarEnteros(n2).equals("entero"));
              int b = Integer.parseInt(n2);
              int r= a+b;
              Bresultado.setText(Float.toString(r));
               }else if (val.validarEnteros(n2).equals("decimal")){
               float t = Float.parseFloat(n2);
             float a = 0;
               float r =  a + t;
               Bresultado.setText(Float.toString(r));
          
                  
          }
         
    }//GEN-LAST:event_btnsumaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String n1= txtnum1.getText();
         String n2= txtnum2.getText();
         if ( opsuma.isSelected()){
             int a = Integer.parseInt(n1);
             int b =Integer.parseInt(n2);
             int c = a +b;
             Bresultado.setText(Integer.toString(c));
         }
        
         if ( opresta.isSelected()){
             int a = Integer.parseInt(n1);
             int b =Integer.parseInt(n2);
             int c = a -b;
             Bresultado.setText(Integer.toString(c));
         }
         if ( opmultiplicacion.isSelected()){
             int a = Integer.parseInt(n1);
             int b =Integer.parseInt(n2);
             int c = a *b;
             Bresultado.setText(Integer.toString(c));
         }
        if ( opdiv.isSelected()){
             float a = Float.parseFloat(n1);
             float b =Float.parseFloat(n2);
             float c = a /b;
             Bresultado.setText(Float.toString(c));
         }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtnum1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnum1KeyTyped
        // TODO add your handling code here:
       int key = evt.getKeyChar();
    if (key==8) {
             c--;  
    }
    
          if (c<0){
              c=0;
          }
             
             if ( (key >= 48 && key<=57) ||  key== 46 ){
           c++;
       } else {
           evt.consume();
         if (c>0){
            btnsuma.setEnabled(true);
              btnresta.setEnabled(true);
               btnmulti.setEnabled(true);
                btndivision.setEnabled(true);
                opsuma.setEnabled(true);
                opresta.setEnabled(true);
                opmultiplicacion.setEnabled(true);
                opdiv.setEnabled(true);
         
         }else{
             btnsuma.setEnabled(false);
              btnresta.setEnabled(false);
               btnmulti.setEnabled(false);
                btndivision.setEnabled(false);
                 opsuma.setEnabled(false);
                opresta.setEnabled(false);
                opmultiplicacion.setEnabled(false);
                opdiv.setEnabled(false);
         
         }
       
       }
    }//GEN-LAST:event_txtnum1KeyTyped

    private void txtnum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnum2ActionPerformed

    private void txtnum2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnum2KeyTyped
        // TODO add your handling code here:
         int key = evt.getKeyChar();
           if (key==8) {
             c2--; 
         }
             if (c<0) {
                 c=0;
             }  
         if ( (key >= 48 && key<=57) ||  key== 46 ){
           c2++;
           
       } else {
           evt.consume();
         if (c2>0){
             btnsuma.setEnabled(true);
              btnresta.setEnabled(true);
               btnmulti.setEnabled(true);
                btndivision.setEnabled(true);
                opsuma.setEnabled(true);
                opresta.setEnabled(true);
                opmultiplicacion.setEnabled(true);
                opdiv.setEnabled(true);
         }
        
         else{
              btnsuma.setEnabled(false);
              btnresta.setEnabled(false);
               btnmulti.setEnabled(false);
                btndivision.setEnabled(false);
                 opsuma.setEnabled(false);
                opresta.setEnabled(false);
                opmultiplicacion.setEnabled(false);
                opdiv.setEnabled(false);
             
         
         }
       
         }
        
    }//GEN-LAST:event_txtnum2KeyTyped

    private void btnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestaActionPerformed
        // TODO add your handling code here:
          String n1,n2;
         n1 = txtnum1.getText();
         n2 = txtnum2.getText();
          Validaciones val = new Validaciones();
          if (val.validarEnteros(n1).equals("decimal")){
              //JOptionPane.showMessageDialog(null, "Hola");
              float a= Float.parseFloat(n1);
              if (val.validarEnteros(n2).equals("decimal")){
                  float b = Float.parseFloat(n2);
                  float r = a - b;
                  Bresultado.setText(Float.toString(r));
                    }else if (val.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                float r = a - b;
                Bresultado.setText(Float.toString(r));
            
                  
              }
          }else if(val.validarEnteros(n1).equals("entero")){
              int a = Integer.parseInt(n1);
              if (val.validarEnteros(n2).equals("entero"));
              int b = Integer.parseInt(n2);
              int r= a-b;
              Bresultado.setText(Float.toString(r));
               }else if (val.validarEnteros(n2).equals("decimal")){
               float t = Float.parseFloat(n2);
              float a = 0;
               float r = a - t;
               Bresultado.setText(Float.toString(r));
          
                  
          }
    }//GEN-LAST:event_btnrestaActionPerformed

    private void btnmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiActionPerformed
        // TODO add your handling code here:
          String n1,n2;
         n1 = txtnum1.getText();
         n2 = txtnum2.getText();
          Validaciones val = new Validaciones();
          if (val.validarEnteros(n1).equals("decimal")){
              //JOptionPane.showMessageDialog(null, "Hola");
              float a= Float.parseFloat(n1);
              if (val.validarEnteros(n2).equals("decimal")){
                  float b = Float.parseFloat(n2);
                  float r = a * b;
                  Bresultado.setText(Float.toString(r));
                    }else if (val.validarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                float r = a * b;
                Bresultado.setText(Float.toString(r));
            
                  
              }
          }else if(val.validarEnteros(n1).equals("entero")){
              int a = Integer.parseInt(n1);
              if (val.validarEnteros(n2).equals("entero"));
              int b = Integer.parseInt(n2);
              int r= a*b;
              Bresultado.setText(Float.toString(r));
               }else if (val.validarEnteros(n2).equals("decimal")){
               float t = Float.parseFloat(n2);
               float r =  t;
               Bresultado.setText(Float.toString(r));
          
                  
          }
    }//GEN-LAST:event_btnmultiActionPerformed

    private void btndivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivisionActionPerformed
        // TODO add your handling code here:
          String n1,n2;
         n1 = txtnum1.getText();
         n2 = txtnum2.getText();
          Validaciones val = new Validaciones();
          if (val.validarEnteros(n1).equals("decimal")){
              //JOptionPane.showMessageDialog(null, "Hola");
              float a= Float.parseFloat(n1);
              if (val.validarEnteros(n2).equals("decimal")){
                  float b = Float.parseFloat(n2);
                  float r = a / b;
                  Bresultado.setText(Float.toString(r));
                    }else if (val.validarEnteros(n2).equals("entero")){
                float b = Float.parseFloat(n2);
                float r = a / b;
                Bresultado.setText(Float.toString(r));
            
                  
              }
          }else if(val.validarEnteros(n1).equals("entero")){
              int a = Integer.parseInt(n1);
              if (val.validarEnteros(n2).equals("entero"));
              float b = Float.parseFloat(n2);
              float r= a/b;
              Bresultado.setText(Float.toString(r));
               }else if (val.validarEnteros(n2).equals("decimal")){
               float t = Float.parseFloat(n2);
              float a = 0;
               float r = a / t;
               Bresultado.setText(Float.toString(r));
          
                  
          }
    }//GEN-LAST:event_btndivisionActionPerformed

    private void opsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opsumaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_opsumaActionPerformed

    private void oprestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oprestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oprestaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bresultado;
    private javax.swing.JButton btndivision;
    private javax.swing.JButton btnmulti;
    private javax.swing.JButton btnresta;
    private javax.swing.JButton btnsuma;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton opdiv;
    private javax.swing.JRadioButton opmultiplicacion;
    private javax.swing.JRadioButton opresta;
    private javax.swing.JRadioButton opsuma;
    private javax.swing.JTextField txtnum1;
    private javax.swing.JTextField txtnum2;
    // End of variables declaration//GEN-END:variables
}
